# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from clien_bot.models.base_model_ import Model
from clien_bot import util


class Failure(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, error_message: str=None, error_code: int=None):  # noqa: E501
        """Failure - a model defined in Swagger

        :param error_message: The error_message of this Failure.  # noqa: E501
        :type error_message: str
        :param error_code: The error_code of this Failure.  # noqa: E501
        :type error_code: int
        """
        self.swagger_types = {
            'error_message': str,
            'error_code': int
        }

        self.attribute_map = {
            'error_message': 'error_message',
            'error_code': 'error_code'
        }

        self._error_message = error_message
        self._error_code = error_code

    @classmethod
    def from_dict(cls, dikt) -> 'Failure':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Failure of this Failure.  # noqa: E501
        :rtype: Failure
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error_message(self) -> str:
        """Gets the error_message of this Failure.


        :return: The error_message of this Failure.
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message: str):
        """Sets the error_message of this Failure.


        :param error_message: The error_message of this Failure.
        :type error_message: str
        """

        self._error_message = error_message

    @property
    def error_code(self) -> int:
        """Gets the error_code of this Failure.


        :return: The error_code of this Failure.
        :rtype: int
        """
        return self._error_code

    @error_code.setter
    def error_code(self, error_code: int):
        """Sets the error_code of this Failure.


        :param error_code: The error_code of this Failure.
        :type error_code: int
        """

        self._error_code = error_code
